In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
news = pd.read_csv("https://raw.githubusercontent.com/austinyu/CSC395-Final-Project/main/dataset_processed/fakeNews_titleStemming_Sampled.csv")
news

,Unnamed: 0,000,10,100,11,151,17,189,1970,1981,...,york,you,young,your,youtub,zero,ziff,zika,zone,label
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,3,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,295,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
296,296,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
297,297,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
298,298,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
299,299,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [3]:
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

news_predictors, predictors_test, news_target, target_test = train_test_split(news.drop(columns = ['label']), 
                                                          news['label'], 
                                                          random_state=7, 
                                                          test_size=0.3)

In [4]:
clf1 = LogisticRegression(max_iter=10000)
clf2 = svm.SVC(C= 1, kernel='linear')
clf3 = RandomForestClassifier()
eclf1 = VotingClassifier(estimators=[('lr', clf1), ('svm', clf2), ('rf', clf3)], voting='hard')

In [6]:
eclf1 = eclf1.fit(news_predictors, news_target)
prediction = eclf1.predict(predictors_test)

accuracy = accuracy_score(target_test, prediction)
print("Î‘ccuracy = ", accuracy * 100, "%")

f1 = f1_score(target_test, prediction, average='macro')
print("F1 score = ", f1 * 100, "%")

Î‘ccuracy =  85.55555555555556 %
F1 score =  85.33650833437775 %